module.exports = [
  {
    methodName: 'customer_insert',
    result: [
      {
        smsOptIn: 'Y',
        optIn: 'Y',
        id: '14880',
        title: '',
        lastname: '',
        firstname: '',
        middlename: '',
        prefix: '',
        suffix: '',
        initials: '',
        gender: 'UNKNOWN',
        maritalStatus: 'UNKNOWN',
        birthday: '0000-00-00',
        birthplace: '',
        address: '',
        address2: '',
        address3: '',
        addressNumber: '',
        addressNumberSuffix: '',
        zipCode: '',
        poBox: '0',
        city: '',
        state: '',
        country: '',
        companyName: '',
        department: '',
        alternateAddress: '',
        alternateAddress2: '',
        alternateAddress3: '',
        alternateAddressNumber: '',
        alternateAddressNumberSuffix: '',
        alternateZipCode: '',
        alternateCity: '',
        alternateState: '',
        alternateCountry: '',
        contactMan: '',
        jobTitle: '',
        workPhone: '',
        workExtension: '',
        workMobile: '',
        homePhone: '',
        mobilePhone: '',
        faxNumber: '',
        emailAddress: '',
        alternateEmailAddress: '',
        emailType: 'MULTIPART',
        mailStatus: 'ACTIVE',
        softBounceCount: '0',
        hardBounceCount: '0',
        website: '',
        imageUrl: '',
        status: 'SUSPECT',
        externalId: '',
        userName: '',
        password: '',
        createdBy: 'SOAP user (int)',
        createdAt: '2017-06-23 18:01:57',
        modifiedBy: 'SOAP user (int)',
        modifiedAt: '2017-06-23 18:01:57',
        options: []
      }
    ]
  }
]
