module.exports = {
  customer: {
    smsOptIn: 'Y',
    optIn: 'Y',
    id: '14880',
    title: '',
    lastname: '',
    firstname: '',
    middlename: '',
    prefix: '',
    suffix: '',
    initials: '',
    gender: 'UNKNOWN',
    maritalStatus: 'UNKNOWN',
    birthday: '0000-00-00',
    birthplace: '',
    address: '',
    address2: '',
    address3: '',
    addressNumber: '',
    addressNumberSuffix: '',
    zipCode: '',
    poBox: '0',
    city: '',
    state: '',
    country: '',
    companyName: '',
    department: '',
    alternateAddress: '',
    alternateAddress2: '',
    alternateAddress3: '',
    alternateAddressNumber: '',
    alternateAddressNumberSuffix: '',
    alternateZipCode: '',
    alternateCity: '',
    alternateState: '',
    alternateCountry: '',
    contactMan: '',
    jobTitle: '',
    workPhone: '',
    workExtension: '',
    workMobile: '',
    homePhone: '',
    mobilePhone: '',
    faxNumber: '',
    emailAddress: '',
    alternateEmailAddress: '',
    emailType: 'MULTIPART',
    mailStatus: 'ACTIVE',
    softBounceCount: '0',
    hardBounceCount: '0',
    website: '',
    imageUrl: '',
    status: 'SUSPECT',
    externalId: '',
    userName: '',
    password: '',
    createdBy: 'SOAP user (int)',
    createdAt: '2017-06-23 18:01:57',
    modifiedBy: 'SOAP user (int)',
    modifiedAt: '2017-06-23 18:01:57',
    options: []
  },
  email: {
    folder: '/',
    class: 'EMAIL',
    id: '59846',
    type: 'MULTIPART',
    templateId: '0',
    name: 'test-name',
    campaignId: '0',
    fromAddress: 'user@example.com',
    fromName: 'Smith',
    replyToAddress: '',
    replyToName: '',
    subject: 'test-name',
    createdBy: 'SOAP user (ext)',
    createdAt: '2017-07-05 14:34:41',
    modifiedBy: 'SOAP user (ext)',
    modifiedAt: '2017-07-05 14:34:41',
    htmlContent: '<html><body><h1>Newsletter</h1>HTML body</body></html>',
    htmlBlocks: null,
    textContent: 'Newsletter text body'
  },
  empty_email: {
    type: 'MULTIPART'
  }
}
